services:
#    ibw_jobeet.example:
#        class: Ibw\JobeetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    ibw.jobeet.admin.affiliate:
            class: Ibw\JobeetBundle\Admin\AffiliateAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: jobeet, label: Affiliates }
            arguments:
                - ~
                - Ibw\JobeetBundle\Entity\Affiliate
                - 'IbwJobeetBundle:AffiliateAdmin'